services:
  securecapitaapp:
    container_name: usermanagementappcontainer
    build: .
    image: usermanagementappc:v1
    ports:
      - 80:80
    expose:
      - 80
    networks:
      - internalnet

networks:
  internalnet:
    driver: bridge
